SNAPSHOT_DIR=src/snapshots/src
LIB_OBJECTS+=\
	$(SNAPSHOT_DIR)/block_manager.o \
	$(SNAPSHOT_DIR)/space_map.o \
	$(SNAPSHOT_DIR)/btree.o \
	$(SNAPSHOT_DIR)/transaction_manager.o \

#	$(SNAPSHOT_DIR)/device.o
#	$(SNAPSHOT_DIR)/persistent_estore.o \
# 	$(SNAPSHOT_DIR)/union_estore.o \